title:              Diario de un parkinsoniano
email:              diariodeunparkinsoniano@outlook.es
description:        Blog personal de una persona que convive con el Parkinson
author:             diariodeunparkinsoniano
date:               2016-11-27

authors:
    diariodeunparkinsoniano:
      name:           Antonio Liberal
      site:           https://diariodeunparkinsoniano.cls-system.es/
      avatar:         assets/images/diariodeunparkinsoniano.gif
      bio:            "Hola, soy Antonio, el autor de este blog. ¡Espero que lo disfrutes!"
      email:          diariodeunparkinsoniano@outlook.es
      twitter:        antoniolibe


baseurl:            ""
url:                "https://diariodeunparkinsoniano.cls-system.es"
disqus: 'diariodeunparkinsoniano'
# Social Profiles
twitter_username:   antoniolibe
github_username:    
facebook_username:  a.liberal.irigoyen 
instagram_username:  
linkedin_username:  antonio-liberal-irigoyen-3233053a

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-175471186-2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/post/page:num/"
excerpt_separator: <!–break–>
permalink: /post/:year/:month/:day/:title
page:
    background: '/img/bg-contact.jpg'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-email-protect

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, .vs]

defaults:
  -
    scope:
      path:            "assets/ebooksXXX/*.pdf"
    values:
      sitemap:         false
      seo:
        robots:        [noindex,nofollow]
  -
    scope:
      path:            "assets/ebooksXXX/*.epub"
    values:
      sitemap:         false
      seo:
        robots:        [noindex,nofollow]
  -
    scope:
      path:            "assets/ebooksXXX/*.mobi"
    values:
      sitemap:         false      
      seo:
        robots:        [noindex,nofollow]
